{% set data = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}

package:
  name: {{ data.get("name") }}
  version: {{ data.get("version") }}

source:
  path: ../

requirements:
  host:
    - python
    - pip

  run:
    - python
    - ipython

