name: {{ cookiecutter.project_name }}-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - black==19.3b0
  - flake8==3.7.9
  - flake8-blind-except==0.1.1
  - flake8-builtins==1.4.2
  - flake8-copyright==0.2.2
  - flake8-docstrings==1.5.0
  - flake8-mutable==1.2.0
  - flake8-pep3101==1.3.0
  - flake8-quotes==2.1.0
  - flake8-self==0.2.2
  - ipython==7.11.1
  - pep8-naming
  - pip
  - pip:
      - flake8-bandit==2.1.2
      - flake8-bugbear==20.1.2
      - flake8-debugger==3.2.1
      - flake8-logging-format==0.6.0
      - flake8-print==3.1.4
  - pre-commit==1.21.0
  - rope==1.21.0
  - twine==3.1.1

